export const CLICK_SQUARE = 'CLICK_SQUARE';
export const RESET_BOARD = 'RESET_BOARD';
export const BACK_BOARD = 'BACK_BOARD';
export const ORDER_HISTORY = 'ORDER_HISTORY';

export const CHANGE_NOTIFY_ERROR_REGISTER = 'CHANGE_NOTIFY_ERROR_REGISTER';
export const CHANGE_NOTIFY_ERROR_LOGIN = 'CHANGE_NOTIFY_ERROR_LOGIN';
